import type { Metadata } from "next";
import {  Space_Grotesk, Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans ({
  variable: "--font-plus_jakarta_sans",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space_grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Panda SMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta.variable} ${spaceGrotesk.variable} antialiased font-Plus `}
      >
        {children}
      </body>
    </html>
  );
}
